package com.ticketbox.ui.design

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color
import com.ticketbox.domain.model.AppSkin

data class ChartTokens(
    val series: List<Color>,
    val sequentialFrom: Color,
    val sequentialTo: Color,
    val divergingNegative: Color,
    val divergingZero: Color,
    val divergingPositive: Color,
    val axis: Color,
    val axisLabel: Color,
    val grid: Color,
    val gridEmphasis: Color,
    val tooltipBg: Color,
    val tooltipFg: Color,
    val tooltipBorder: Color,
    val legendFg: Color,
    val legendMarker: Color,
    val sankeyRibbon: Color,
    val sankeyRibbonEmphasis: Color,
    val overspend: Color,
    val empty: Color,
)

val LocalChartTokens = compositionLocalOf { chartTokensForSkin(AppSkin.Default) }

fun chartTokensForSkin(skin: AppSkin): ChartTokens {
    return when (skin) {
        AppSkin.Pine -> ChartTokens(
            series = listOf(
                Color(0xFF185B4F),
                Color(0xFFC8995F),
                Color(0xFF2D7A80),
                Color(0xFFA86A52),
                Color(0xFF5E8A6F),
                Color(0xFFD9A847),
                Color(0xFF4A6E84),
                Color(0xFF7A5670),
            ),
            sequentialFrom = Color(0xFFDCEBE5),
            sequentialTo = Color(0xFF0E433A),
            divergingNegative = Color(0xFFB94B3F),
            divergingZero = Color(0xFFE9E4D6),
            divergingPositive = Color(0xFF2F7E64),
            axis = Color(0xFF8C9C95),
            axisLabel = Color(0xFF5E6B65),
            grid = Color(0x33A2B5AA),
            gridEmphasis = Color(0x66185B4F),
            tooltipBg = Color(0xFF0F2A24),
            tooltipFg = Color(0xFFF1F6F2),
            tooltipBorder = Color(0xFF1A3C34),
            legendFg = Color(0xFF1D2524),
            legendMarker = Color(0xFFFFFCF7),
            sankeyRibbon = Color(0x4D2B7567),
            sankeyRibbonEmphasis = Color(0xCC185B4F),
            overspend = Color(0xFFB94B3F),
            empty = Color(0xFFCFD6D1),
        )
        AppSkin.Pomelo -> ChartTokens(
            series = listOf(
                Color(0xFFE6981B),
                Color(0xFF2D7A80),
                Color(0xFFCB6C2F),
                Color(0xFF6A8C3F),
                Color(0xFF8A6A2D),
                Color(0xFF45A6A3),
                Color(0xFFB05E91),
                Color(0xFF4D5F8E),
            ),
            sequentialFrom = Color(0xFFFFEFCB),
            sequentialTo = Color(0xFF8B5A0B),
            divergingNegative = Color(0xFFB94A2A),
            divergingZero = Color(0xFFF1E6D0),
            divergingPositive = Color(0xFF4F8A48),
            axis = Color(0xFFAA9870),
            axisLabel = Color(0xFF6F5C36),
            grid = Color(0x33D8C49A),
            gridEmphasis = Color(0x66E6981B),
            tooltipBg = Color(0xFF2F2410),
            tooltipFg = Color(0xFFFFF6E6),
            tooltipBorder = Color(0xFF513A18),
            legendFg = Color(0xFF25221C),
            legendMarker = Color(0xFFFFFCF7),
            sankeyRibbon = Color(0x4DE6981B),
            sankeyRibbonEmphasis = Color(0xCC9B6306),
            overspend = Color(0xFFB94A2A),
            empty = Color(0xFFE0D2B3),
        )
        AppSkin.Harbor -> ChartTokens(
            series = listOf(
                Color(0xFF245D78),
                Color(0xFFD5A35D),
                Color(0xFF185B4F),
                Color(0xFFA86A52),
                Color(0xFF3E92AE),
                Color(0xFF6B7F4D),
                Color(0xFFB87A48),
                Color(0xFF5A4E78),
            ),
            sequentialFrom = Color(0xFFDDEAF0),
            sequentialTo = Color(0xFF12384C),
            divergingNegative = Color(0xFFB04A3C),
            divergingZero = Color(0xFFE6E3D5),
            divergingPositive = Color(0xFF2D7A80),
            axis = Color(0xFF8FA1A6),
            axisLabel = Color(0xFF52646A),
            grid = Color(0x339FB4BB),
            gridEmphasis = Color(0x66245D78),
            tooltipBg = Color(0xFF112A35),
            tooltipFg = Color(0xFFF1F6F7),
            tooltipBorder = Color(0xFF1E4254),
            legendFg = Color(0xFF1E2524),
            legendMarker = Color(0xFFFFFCF7),
            sankeyRibbon = Color(0x4D2F7B92),
            sankeyRibbonEmphasis = Color(0xCC245D78),
            overspend = Color(0xFFB04A3C),
            empty = Color(0xFFD0D7D9),
        )
        AppSkin.Berry -> ChartTokens(
            series = listOf(
                Color(0xFFA83C5A),
                Color(0xFF8B7A65),
                Color(0xFF3E7A6A),
                Color(0xFFC4657F),
                Color(0xFF6F4C7A),
                Color(0xFFB8814D),
                Color(0xFF457495),
                Color(0xFF8B5048),
            ),
            sequentialFrom = Color(0xFFF2D7DF),
            sequentialTo = Color(0xFF6E2238),
            divergingNegative = Color(0xFFA83C5A),
            divergingZero = Color(0xFFE6DDE0),
            divergingPositive = Color(0xFF3E7A6A),
            axis = Color(0xFFAA8E96),
            axisLabel = Color(0xFF6E5660),
            grid = Color(0x33D2B6C0),
            gridEmphasis = Color(0x66A83C5A),
            tooltipBg = Color(0xFF34141E),
            tooltipFg = Color(0xFFF8E9EE),
            tooltipBorder = Color(0xFF52202F),
            legendFg = Color(0xFF251F22),
            legendMarker = Color(0xFFFFFAFC),
            sankeyRibbon = Color(0x4DC4657F),
            sankeyRibbonEmphasis = Color(0xCCA83C5A),
            overspend = Color(0xFF7E1F36),
            empty = Color(0xFFDECCD2),
        )
        AppSkin.Night -> ChartTokens(
            series = listOf(
                Color(0xFF2BB49A),
                Color(0xFFD2A46E),
                Color(0xFF84BCD4),
                Color(0xFFEC9C8F),
                Color(0xFFAFC97A),
                Color(0xFFB78ED3),
                Color(0xFFF5C76A),
                Color(0xFF6FB1AD),
            ),
            sequentialFrom = Color(0xFF0A2A26),
            sequentialTo = Color(0xFF7CDDB8),
            divergingNegative = Color(0xFFEC9C8F),
            divergingZero = Color(0xFF1A3038),
            divergingPositive = Color(0xFF7CDDB8),
            axis = Color(0xFF435E66),
            axisLabel = Color(0xFFB6C6C8),
            grid = Color(0x332D4A52),
            gridEmphasis = Color(0x662BB49A),
            tooltipBg = Color(0xFF051518),
            tooltipFg = Color(0xFFE7F1EF),
            tooltipBorder = Color(0xFF143138),
            legendFg = Color(0xFFE7F1EF),
            legendMarker = Color(0xFF0D2027),
            sankeyRibbon = Color(0x4D2BB49A),
            sankeyRibbonEmphasis = Color(0xCC7CDDB8),
            overspend = Color(0xFFEC9C8F),
            empty = Color(0xFF243A42),
        )
    }
}
