package com.ticketbox.ui.design

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color
import com.ticketbox.domain.model.AppSkin

data class ReceiptStubPalette(
    val paperTop: Color,
    val paperBottom: Color,
    val border: Color,
    val line: Color,
    val footer: Color,
)

data class ThemeVisuals(
    val primary: Color,
    val primaryDark: Color,
    val accent: Color,
    val backgroundTop: Color,
    val backgroundBottom: Color,
    val heroGradient: List<Color>,
    val heroGradientStart: Color,
    val heroGradientEnd: Color,
    val heroGlow: Color,
    val glassTint: Color,
    val solidCard: Color,
    val chipSelected: Color,
    val chipUnselected: Color,
    val shadowTint: Color,
    val illustrationTint: Color,
    val warningTint: Color,
    val warmMist: Color,
    val coolMist: Color,
    val surfaceRaised: Color,
    val focusRing: Color,
    val receiptStub: ReceiptStubPalette,
    // v0.10.1 镜像 shared/tokens.css 余下 surface / text / brand 语义,
    // 让三端语义对照表完整。原本由 MaterialTheme.colorScheme 兜底的字段
    // (onBackground/onSurfaceVariant 等) 现在通过显式字段表达,Android Screen
    // 不再依赖 Material You 默认。
    val surfaceNav: Color,
    val surfaceSunken: Color,
    val textDefault: Color,
    val textMuted: Color,
    val textMeta: Color,
    val textFaint: Color,
    val textOnPrimary: Color,
    val brandPrimaryBg: Color,
)

val LocalThemeVisuals = compositionLocalOf { themeVisualsForSkin(AppSkin.Default) }

fun themeVisualsForSkin(skin: AppSkin): ThemeVisuals {
    return when (skin) {
        AppSkin.Paper -> ThemeVisuals(
            primary = Color(0xFF8A5A2B),
            primaryDark = Color(0xFF6F4621),
            accent = Color(0xFFD6B487),
            backgroundTop = Color(0xFFFBF8F1),
            backgroundBottom = Color(0xFFF3EFE6),
            heroGradient = listOf(
                Color(0xFF8A5A2B),
                Color(0xFFA86F38),
                Color(0xFF6F4621),
            ),
            heroGradientStart = Color(0xFF8A5A2B),
            heroGradientEnd = Color(0xFF6F4621),
            heroGlow = Color(0xFFD6B487),
            glassTint = Color(0xFFFBF8F1),
            solidCard = Color(0xFFFBF8F1),
            chipSelected = Color(0xFFEFE1CB),
            chipUnselected = Color(0xFFF5F0E3),
            shadowTint = Color(0xFF6F4621),
            illustrationTint = Color(0xFFD6B487),
            warningTint = Color(0xFFA4361C),
            warmMist = Color(0xFFEAD8B8),
            coolMist = Color(0xFFC8C2B3),
            surfaceRaised = Color(0xFFFFFFFF),
            focusRing = Color(0xFF8A5A2B),
            receiptStub = ReceiptStubPalette(
                paperTop = Color(0xFFFFFBF3),
                paperBottom = Color(0xFFF1E9DB),
                border = Color(0xFFE2D8C8),
                line = Color(0xFFBDB7AB),
                footer = Color(0xFFE0D5C4),
            ),
            surfaceNav = Color(0xFF1C1A18),
            surfaceSunken = Color(0xFFF5F0E3),
            textDefault = Color(0xFF1C1A18),
            textMuted = Color(0xFF4A463F),
            textMeta = Color(0xFF807968),
            textFaint = Color(0xFFB3AD9D),
            textOnPrimary = Color(0xFFFBF8F1),
            brandPrimaryBg = Color(0xFFEFE1CB),
        )
        AppSkin.Mono -> ThemeVisuals(
            primary = Color(0xFF0E0E0C),
            primaryDark = Color(0xFF000000),
            accent = Color(0xFF6F6E6A),
            backgroundTop = Color(0xFFFAFAF8),
            backgroundBottom = Color(0xFFEDEDEA),
            heroGradient = listOf(
                Color(0xFF0E0E0C),
                Color(0xFF2C2B29),
                Color(0xFF000000),
            ),
            heroGradientStart = Color(0xFF0E0E0C),
            heroGradientEnd = Color(0xFF000000),
            heroGlow = Color(0xFFADACA7),
            glassTint = Color(0xFFFAFAF8),
            solidCard = Color(0xFFFAFAF8),
            chipSelected = Color(0xFFE3E2DD),
            chipUnselected = Color(0xFFF1F0ED),
            shadowTint = Color(0xFF0E0E0C),
            illustrationTint = Color(0xFFADACA7),
            warningTint = Color(0xFF8E1D12),
            warmMist = Color(0xFFE7DBC0),
            coolMist = Color(0xFFB8B7B3),
            surfaceRaised = Color(0xFFFFFFFF),
            focusRing = Color(0xFF0E0E0C),
            receiptStub = ReceiptStubPalette(
                paperTop = Color(0xFFFAFAF8),
                paperBottom = Color(0xFFEDEDEA),
                border = Color(0xFFD7D6D1),
                line = Color(0xFFACABA6),
                footer = Color(0xFFE0DFDA),
            ),
            surfaceNav = Color(0xFF0E0E0C),
            surfaceSunken = Color(0xFFF1F0ED),
            textDefault = Color(0xFF0E0E0C),
            textMuted = Color(0xFF3A3A37),
            textMeta = Color(0xFF6F6E6A),
            textFaint = Color(0xFFADACA7),
            textOnPrimary = Color(0xFFFAFAF8),
            brandPrimaryBg = Color(0xFFE3E2DD),
        )
        AppSkin.Midnight -> ThemeVisuals(
            primary = Color(0xFFD6B487),
            primaryDark = Color(0xFFB89564),
            accent = Color(0xFF8A6A3E),
            backgroundTop = Color(0xFF15171C),
            backgroundBottom = Color(0xFF0C0D10),
            heroGradient = listOf(
                Color(0xFF8A6A3E),
                Color(0xFFB89564),
                Color(0xFF15171C),
            ),
            heroGradientStart = Color(0xFF8A6A3E),
            heroGradientEnd = Color(0xFF15171C),
            heroGlow = Color(0xFFD6B487),
            glassTint = Color(0xFF1C1F25),
            solidCard = Color(0xFF15171C),
            chipSelected = Color(0xFF2A2D35),
            chipUnselected = Color(0xFF1C1F25),
            shadowTint = Color(0xFF000000),
            illustrationTint = Color(0xFF3A3E48),
            warningTint = Color(0xFFD97757),
            warmMist = Color(0xFF4D3617),
            coolMist = Color(0xFF8A6A3E),
            surfaceRaised = Color(0xFF222530),
            focusRing = Color(0xFFD6B487),
            receiptStub = ReceiptStubPalette(
                paperTop = Color(0xFF252830),
                paperBottom = Color(0xFF1A1D24),
                border = Color(0xFF3A3E48),
                line = Color(0xFF8A806F),
                footer = Color(0xFF343742),
            ),
            surfaceNav = Color(0xFF08090C),
            surfaceSunken = Color(0xFF1C1F25),
            textDefault = Color(0xFFE9E7DF),
            textMuted = Color(0xFFB8B4A8),
            textMeta = Color(0xFF807C70),
            textFaint = Color(0xFF4D4A44),
            textOnPrimary = Color(0xFF15171C),
            // tokens.css 用 rgba(214,180,135,0.14) = alpha 0x24,这里直接表示 argb。
            brandPrimaryBg = Color(0x24D6B487),
        )
    }
}
