package com.ticketbox.ui.design

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color
import com.ticketbox.domain.model.AppSkin

data class ThemeVisuals(
    val primary: Color,
    val primaryDark: Color,
    val accent: Color,
    val backgroundTop: Color,
    val backgroundBottom: Color,
    val heroGradient: List<Color>,
    val heroGradientStart: Color,
    val heroGradientEnd: Color,
    val heroGlow: Color,
    val glassTint: Color,
    val solidCard: Color,
    val chipSelected: Color,
    val chipUnselected: Color,
    val shadowTint: Color,
    val illustrationTint: Color,
    val warningTint: Color,
    val warmMist: Color,
    val coolMist: Color,
    val surfaceRaised: Color,
    val focusRing: Color,
)

val LocalThemeVisuals = compositionLocalOf { themeVisualsForSkin(AppSkin.Default) }

fun themeVisualsForSkin(skin: AppSkin): ThemeVisuals {
    return when (skin) {
        AppSkin.Pine -> ThemeVisuals(
            primary = Color(0xFF185B4F),
            primaryDark = Color(0xFF0E433A),
            accent = Color(0xFFC8995F),
            backgroundTop = Color(0xFFF8F7EF),
            backgroundBottom = Color(0xFFE2EEE9),
            heroGradient = listOf(
                Color(0xFF185B4F),
                Color(0xFF2B7567),
                Color(0xFF0F443B),
            ),
            heroGradientStart = Color(0xFF185B4F),
            heroGradientEnd = Color(0xFF0F443B),
            heroGlow = Color(0xFF8FC2AE),
            glassTint = Color(0xFFFFFCF4),
            solidCard = Color(0xFFFFFCF7),
            chipSelected = Color(0xFFDDEBE5),
            chipUnselected = Color(0xFFF8FAF5),
            shadowTint = Color(0xFF476F64),
            illustrationTint = Color(0xFFD9CDBA),
            warningTint = Color(0xFFE0A24F),
            warmMist = Color(0xFFF1E2C9),
            coolMist = Color(0xFFA6C2B1),
            surfaceRaised = Color(0xFFFFFFFF),
            focusRing = Color(0xFF185B4F),
        )
        AppSkin.Harbor -> ThemeVisuals(
            primary = Color(0xFF245D78),
            primaryDark = Color(0xFF16465E),
            accent = Color(0xFFD5A35D),
            backgroundTop = Color(0xFFFAF7EF),
            backgroundBottom = Color(0xFFD9EAF0),
            heroGradient = listOf(
                Color(0xFF245D78),
                Color(0xFF2F7B92),
                Color(0xFF185B4F),
            ),
            heroGradientStart = Color(0xFF245D78),
            heroGradientEnd = Color(0xFF185B4F),
            heroGlow = Color(0xFF91C5D7),
            glassTint = Color(0xFFFFFCF5),
            solidCard = Color(0xFFFFFCF7),
            chipSelected = Color(0xFFDCEAEF),
            chipUnselected = Color(0xFFF8FBFA),
            shadowTint = Color(0xFF406A78),
            illustrationTint = Color(0xFFD8C9AF),
            warningTint = Color(0xFFD5A35D),
            warmMist = Color(0xFFF0DDC0),
            coolMist = Color(0xFF9FC9D8),
            surfaceRaised = Color(0xFFFFFFFF),
            focusRing = Color(0xFF245D78),
        )
        AppSkin.Pomelo -> ThemeVisuals(
            primary = Color(0xFFE6981B),
            primaryDark = Color(0xFF9B6306),
            accent = Color(0xFF2D7A80),
            backgroundTop = Color(0xFFFFF8EA),
            backgroundBottom = Color(0xFFF1E6D0),
            heroGradient = listOf(
                Color(0xFFCE7F12),
                Color(0xFFE8A83F),
                Color(0xFF875C17),
            ),
            heroGradientStart = Color(0xFFCE7F12),
            heroGradientEnd = Color(0xFF875C17),
            heroGlow = Color(0xFFFFD686),
            glassTint = Color(0xFFFFFCF5),
            solidCard = Color(0xFFFFFCF7),
            chipSelected = Color(0xFFFFE7BB),
            chipUnselected = Color(0xFFFFFBF2),
            shadowTint = Color(0xFFB78331),
            illustrationTint = Color(0xFFE2C99E),
            warningTint = Color(0xFFE6981B),
            warmMist = Color(0xFFFFD994),
            coolMist = Color(0xFFDCE8D9),
            surfaceRaised = Color(0xFFFFFFFF),
            focusRing = Color(0xFFCE7F12),
        )
        AppSkin.Berry -> ThemeVisuals(
            primary = Color(0xFFA83C5A),
            primaryDark = Color(0xFF7B2840),
            accent = Color(0xFF8B7A65),
            backgroundTop = Color(0xFFFFF4F7),
            backgroundBottom = Color(0xFFF0E7EB),
            heroGradient = listOf(
                Color(0xFFA83C5A),
                Color(0xFFC4657F),
                Color(0xFF743049),
            ),
            heroGradientStart = Color(0xFFA83C5A),
            heroGradientEnd = Color(0xFF743049),
            heroGlow = Color(0xFFEAA2B5),
            glassTint = Color(0xFFFFFAFC),
            solidCard = Color(0xFFFFFAFC),
            chipSelected = Color(0xFFF2D7DF),
            chipUnselected = Color(0xFFFFF8FA),
            shadowTint = Color(0xFF9F6175),
            illustrationTint = Color(0xFFE3C7CF),
            warningTint = Color(0xFFC58A4D),
            warmMist = Color(0xFFF1D4C3),
            coolMist = Color(0xFFD7E4DD),
            surfaceRaised = Color(0xFFFFFFFF),
            focusRing = Color(0xFFA83C5A),
        )
        AppSkin.Night -> ThemeVisuals(
            primary = Color(0xFF2BB49A),
            primaryDark = Color(0xFF0A4139),
            accent = Color(0xFFD2A46E),
            backgroundTop = Color(0xFF041018),
            backgroundBottom = Color(0xFF0A2529),
            heroGradient = listOf(
                Color(0xFF0A4139),
                Color(0xFF174D52),
                Color(0xFF07151A),
            ),
            heroGradientStart = Color(0xFF0A4139),
            heroGradientEnd = Color(0xFF07151A),
            heroGlow = Color(0xFF2BB49A),
            glassTint = Color(0xFF10262D),
            solidCard = Color(0xFF0D2027),
            chipSelected = Color(0xFF163F3A),
            chipUnselected = Color(0xFF132A31),
            shadowTint = Color(0xFF061015),
            illustrationTint = Color(0xFF2B4F55),
            warningTint = Color(0xFFD2A46E),
            warmMist = Color(0xFF4D3617),
            coolMist = Color(0xFF2BB49A),
            surfaceRaised = Color(0xFF13313A),
            focusRing = Color(0xFF2BB49A),
        )
    }
}
