#Requires -Version 5.1
<#
.SYNOPSIS
  Start an isolated, throwaway PostgreSQL instance for the backend test suite.

.DESCRIPTION
  PG-only test-lane ergonomics (debt #4 / PG-only slimming). Spins an ephemeral
  PostgreSQL cluster on the contract's local port using the locally installed
  initdb, isolated from forbidden host ports and the Gitea profile. Non-durable
  settings (fsync / synchronous_commit /
  full_page_writes off) because the data is disposable test data.

  Idempotent: if our cluster is already up on the port it is reused; the
  xpj_test / xpj_smoke databases are created only when missing.

  After it prints OK, run the suite with:
    $env:XPJ_TEST_DATABASE_URL = <generated by scripts/write_test_postgres_env.py>
    .\.venv\Scripts\python.exe -m pytest
  (or just `pytest` — the default URL is generated from the same contract.)

  NEVER accepts a contract-reserved host port on Windows. Teardown:
  stop_test_pg.ps1.

.PARAMETER Port
  TCP port for the throwaway cluster. Zero selects the contract profile.

.PARAMETER DataDir
  Cluster data directory. Must be a non-reparse child of the dynamically
  resolved protected test runtime root. Default: xpj_pg_test<Port> under it.

.PARAMETER PostgresBin
  Optional explicit PostgreSQL bin directory for hermetic CI. The same active
  release policy and executable/path validation apply as to local discovery.

.PARAMETER AllowCiPort
  Selects the contract's Gitea profile. Reserved host ports always fail.
#>
[CmdletBinding()]
param(
    [int]$Port = 0,
    [string]$DataDir = '',
    [string]$PostgresBin = '',
    [switch]$AllowCiPort
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot 'test_pg_storage_contract.ps1')
. (Join-Path $PSScriptRoot 'test_pg_auth_contract.ps1')
$contract = Get-XpjTestPostgresContract
$giteaPort = [int]$contract.ports.gitea
$localPort = [int]$contract.ports.local
$forbiddenHostPorts = @($contract.forbidden_host_ports | ForEach-Object { [int]$_ })
if ($Port -eq 0) { $Port = if ($AllowCiPort) { $giteaPort } else { $localPort } }
$null = Initialize-XpjTestPostgresRuntimeRoot
if ([string]::IsNullOrWhiteSpace($DataDir)) {
    $DataDir = Get-XpjTestPostgresDefaultDataDir -Port $Port
}
$DataDir = Resolve-XpjTestPostgresDataDir -DataDir $DataDir
$baseDatabase = [string]$contract.base_database
$smokeDatabase = [string]$contract.smoke_database
$restoreDatabase = [string]$contract.restore_database
$applicationRole = [string]$contract.application_role
$clusterMarker = [string]$contract.cluster_marker

function Resolve-XpjRequestedPostgresBin {
    if ($null -eq $resolvedRequestedPostgresBin) {
        return (Find-XpjPostgresBin)
    }
    return $resolvedRequestedPostgresBin
}

$resolvedRequestedPostgresBin = if ([string]::IsNullOrWhiteSpace($PostgresBin)) {
    $null
}
else {
    Assert-XpjPostgresBinaryWithinReleasePolicy -PostgresBin $PostgresBin
}

if ($Port -in $forbiddenHostPorts -or ($Port -eq $giteaPort -and -not $AllowCiPort)) {
    throw "Refusing port ${Port}: reserved host ports are forbidden and the Gitea port requires the CI lifecycle switch."
}
if ($AllowCiPort -and $Port -ne $giteaPort) {
    throw "The CI lifecycle switch is valid only for the configured Gitea port $giteaPort."
}

function Invoke-XpjPsqlScalar {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$PsqlExe,
        [Parameter(Mandatory = $true)][string]$Connection,
        [Parameter(Mandatory = $true)][string]$Query,
        [Parameter(Mandatory = $true)][string]$Label,
        [switch]$AllowEmpty
    )

    $output = @(
        & $PsqlExe `
            --no-psqlrc `
            --no-password `
            "--dbname=$Connection" `
            --set=ON_ERROR_STOP=1 `
            --tuples-only `
            --no-align `
            "--command=$Query"
    )
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) { throw "$Label failed with exit code $exitCode" }
    $values = @(
        $output |
            ForEach-Object { $_.ToString().Trim() } |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    )
    if ($values.Count -gt 1 -or ($values.Count -eq 0 -and -not $AllowEmpty)) {
        throw "$Label returned an invalid scalar result"
    }
    if ($values.Count -eq 0) { return '' }
    return [string]$values[0]
}

function Invoke-XpjPsqlCommand {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$PsqlExe,
        [Parameter(Mandatory = $true)][string]$Connection,
        [Parameter(Mandatory = $true)][string]$Query,
        [Parameter(Mandatory = $true)][string]$Label
    )

    & $PsqlExe `
        --no-psqlrc `
        --no-password `
        "--dbname=$Connection" `
        --set=ON_ERROR_STOP=1 `
        "--command=$Query" | Out-Null
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) { throw "$Label failed with exit code $exitCode" }
}

function Stop-XpjPostgresStartedByInvocationIfPresent {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$DataDir,
        [Parameter(Mandatory = $true)][ValidateRange(1, 65535)][int]$Port,
        [Parameter(Mandatory = $true)][string]$PostgresExe
    )

    $ownedProcess = $null
    try {
        $ownedProcess = Assert-XpjOwnedPostgresProcess `
            -DataDir $DataDir `
            -Port $Port `
            -PostgresExe $PostgresExe `
            -AllowNoListener
    }
    catch {
        Assert-NoXpjLivePostgresDataDirOwner -DataDir $DataDir -Port $Port
        return
    }
    finally {
        if ($null -ne $ownedProcess) {
            foreach ($process in $ownedProcess.Processes) { $process.Close() }
        }
    }
    Stop-XpjOwnedPostgresProcess `
        -DataDir $DataDir `
        -Port $Port `
        -PostgresExe $PostgresExe
}

$lifecycleLock = Enter-XpjTestPostgresLifecycleLock -DataDir $DataDir -Port $Port
$createdCluster = $false
$startAttemptedByInvocation = $false
$startedByInvocation = $false
$provisioningInstanceId = [Guid]::Empty
try {
$deletionPath = Get-XpjTestPostgresDeletionMarkerPath -DataDir $DataDir
$deletionKind = Get-TicketboxPathEntryKindNoFollow -Path $deletionPath
if ($deletionKind -eq 'File') {
    $deletion = Read-XpjTestPostgresDeletionMarker -DataDir $DataDir -Port $Port
    Remove-XpjTestPostgresCluster `
        -DataDir $DataDir `
        -Port $Port `
        -PostgresExe (Join-Path $deletion.PostgresBin 'postgres.exe')
    Write-Host 'Completed the interrupted PostgreSQL deletion transaction.'
}
elseif ($deletionKind -cne 'Missing') {
    throw "Test PostgreSQL deletion marker is not a plain file: $deletionPath"
}
$provisioningPath = Get-XpjTestPostgresProvisioningMarkerPath -DataDir $DataDir
$provisioningKind = Get-TicketboxPathEntryKindNoFollow -Path $provisioningPath
if ($provisioningKind -notin @('Missing', 'File')) {
    throw "Test PostgreSQL provisioning marker is not a plain file: $provisioningPath"
}
$pendingProvisioning = $null
if ($provisioningKind -eq 'File') {
    $provisioning = Read-XpjTestPostgresProvisioningMarker `
        -DataDir $DataDir `
        -Port $Port
    $provisioningDisposition = Get-XpjPostgresReleaseDisposition `
        -PostgresBin $provisioning.PostgresBin
    if ($provisioningDisposition.State -ceq 'active') {
        $pendingProvisioning = Resolve-XpjTestPostgresProvisioning `
            -DataDir $DataDir `
            -Port $Port
    }
    elseif ($provisioningDisposition.State -ceq 'outside-policy') {
        $provisioningTargetKind = Get-TicketboxPathEntryKindNoFollow -Path $DataDir
        if ($provisioningTargetKind -eq 'Missing') {
            Remove-XpjTestPostgresProvisioningGeneration `
                -DataDir $DataDir `
                -Port $Port `
                -InstanceId $provisioning.InstanceId
        }
        elseif ($provisioningTargetKind -eq 'Directory') {
            $expiredPromotion = Resolve-XpjTestPostgresProvisioning `
                -DataDir $DataDir `
                -Port $Port
            if ($null -eq $expiredPromotion -or -not $expiredPromotion.Completed) {
                throw 'Expired PostgreSQL provisioning could not establish cleanup authority.'
            }
            Remove-XpjTestPostgresCluster `
                -DataDir $DataDir `
                -Port $Port `
                -PostgresExe (Join-Path $provisioning.PostgresBin 'postgres.exe')
        }
        else {
            throw "Expired PostgreSQL provisioning target is not a plain directory: $DataDir"
        }
        Write-Host 'Removed a provisioning generation outside the active release policy.'
    }
    else {
        throw "Unsupported PostgreSQL release disposition: $($provisioningDisposition.State)"
    }
}
if ($null -ne $pendingProvisioning) {
    Remove-XpjTestPostgresBootstrapPasswordFileIfPresent `
        -DataDir $pendingProvisioning.Provisioning.StagingDir
    if (-not $pendingProvisioning.Completed) {
        Remove-XpjTestPostgresProvisioningGeneration `
            -DataDir $DataDir `
            -Port $Port `
            -InstanceId $pendingProvisioning.Provisioning.InstanceId
        Write-Host "Removed the proven interrupted PostgreSQL provisioning generation."
    }
}
Remove-XpjTestPostgresBootstrapPasswordFileIfPresent -DataDir $DataDir
$markerPaths = Get-XpjTestPostgresOwnershipMarkerPaths -DataDir $DataDir
$dataKind = Get-TicketboxPathEntryKindNoFollow -Path $DataDir
$hostMarkerKind = Get-TicketboxPathEntryKindNoFollow -Path $markerPaths.Host
if ($dataKind -notin @('Missing', 'Directory')) {
    throw "Test PostgreSQL data path is not a plain directory: $DataDir ($dataKind)"
}
$ownership = $null
if ($hostMarkerKind -eq 'File') {
    $ownership = Update-XpjTestPostgresOwnershipSchema `
        -DataDir $DataDir `
        -AllowProvisioning:($dataKind -eq 'Missing')
    $ownershipDisposition = Get-XpjPostgresReleaseDisposition `
        -PostgresBin ([string]$ownership.PostgresBin)
    if ($ownershipDisposition.State -ceq 'outside-policy') {
        Remove-XpjTestPostgresCluster `
            -DataDir $DataDir `
            -Port $Port `
            -PostgresExe (Join-Path $ownership.PostgresBin 'postgres.exe')
        $dataKind = 'Missing'
        $hostMarkerKind = 'Missing'
        $ownership = $null
        $pgbin = Resolve-XpjRequestedPostgresBin
        Write-Host 'Replaced an owned disposable cluster outside the active release policy.'
    }
    elseif ($ownershipDisposition.State -ceq 'active') {
        Assert-XpjRequestedPostgresBinMatchesOwnership `
            -RequestedPostgresBin ([string]$resolvedRequestedPostgresBin) `
            -OwnershipPostgresBin ([string]$ownershipDisposition.PostgresBin)
        $pgbin = [string]$ownershipDisposition.PostgresBin
    }
    else {
        throw "Unsupported PostgreSQL release disposition: $($ownershipDisposition.State)"
    }
}
elseif ($dataKind -eq 'Directory') {
    throw "Refusing to start an unmarked PostgreSQL data directory: $DataDir"
}
else {
    $pgbin = Resolve-XpjRequestedPostgresBin
}
$postgresExe = Join-Path $pgbin 'postgres.exe'
if ($dataKind -eq 'Missing' -and $hostMarkerKind -eq 'File') {
    Remove-XpjTestPostgresCluster -DataDir $DataDir -Port $Port -PostgresExe $postgresExe
    $hostMarkerKind = 'Missing'
    $ownership = $null
    $pgbin = Resolve-XpjRequestedPostgresBin
    $postgresExe = Join-Path $pgbin 'postgres.exe'
}
if ($dataKind -eq 'Directory') {
    $authenticationState = Get-XpjTestPostgresAuthenticationState -DataDir $DataDir -Port $Port
    if ($authenticationState -in @('legacy-trust', 'legacy-superuser-only')) {
        Remove-XpjTestPostgresCluster -DataDir $DataDir -Port $Port -PostgresExe $postgresExe
        $dataKind = 'Missing'
        $hostMarkerKind = 'Missing'
        $ownership = $null
        $pgbin = Resolve-XpjRequestedPostgresBin
        $postgresExe = Join-Path $pgbin 'postgres.exe'
        Write-Host 'Replaced the owned disposable legacy authentication cluster with the current role contract.'
    }
}

$alreadyUp = $false
$listening = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue
if ($listening) {
    $identity = Assert-XpjOwnedPostgresProcess -DataDir $DataDir -Port $Port -PostgresExe $postgresExe
    $alreadyUp = $true
    Write-Host "Reusing PostgreSQL already up on $($identity.HostAddress):$Port (datadir=$DataDir)"
}

if (-not $alreadyUp) {
    if ($dataKind -eq 'Missing') {
        $provisioning = New-XpjTestPostgresProvisioning `
            -DataDir $DataDir `
            -PostgresBin $pgbin `
            -Port $Port
        $provisioningInstanceId = $provisioning.InstanceId
        $stagingDataDir = $provisioning.StagingDir
        $createdCluster = $true
        $credential = New-XpjTestPostgresCredential
        $bootstrapPasswordPath = New-XpjTestPostgresBootstrapPasswordFile `
            -DataDir $stagingDataDir `
            -Credential $credential
        try {
            & "$pgbin\initdb.exe" `
                -D $stagingDataDir `
                -U postgres `
                --auth-host=scram-sha-256 `
                --auth-local=scram-sha-256 `
                --pwfile=$bootstrapPasswordPath `
                --set=password_encryption=scram-sha-256 `
                -E UTF8 `
                --locale=C | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "initdb failed" }
        }
        finally {
            Remove-XpjTestPostgresBootstrapPasswordFile `
                -DataDir $stagingDataDir `
                -Path $bootstrapPasswordPath
        }
        Initialize-XpjTestPostgresAuthenticationFiles `
            -DataDir $stagingDataDir `
            -Port $Port `
            -Credential $credential
        $ownershipText = ConvertTo-XpjTestPostgresOwnershipMarkerText `
            -DataDir $DataDir `
            -InstanceId $provisioning.InstanceId `
            -PostgresBin $pgbin
        $stagingMarkerPath = Join-Path $stagingDataDir ([string]$contract.ownership_marker_name)
        Write-XpjTestPostgresProtectedMarker -Path $stagingMarkerPath -Text $ownershipText
        $completedProvisioning = Resolve-XpjTestPostgresProvisioning -DataDir $DataDir -Port $Port
        if ($null -eq $completedProvisioning -or -not $completedProvisioning.Completed) {
            throw "Test PostgreSQL staging generation did not promote: $stagingDataDir"
        }
        $provisioningInstanceId = [Guid]::Empty
    }
    Remove-XpjStalePostmasterIdentity -DataDir $DataDir -PostgresExe $postgresExe
    $opts = "-p $Port -c listen_addresses=127.0.0.1 -c fsync=off -c synchronous_commit=off -c full_page_writes=off"
    $startEnvironment = Enter-XpjCleanPostgresEnvironment
    try {
        $startAttemptedByInvocation = $true
        & "$pgbin\pg_ctl.exe" -D $DataDir -o $opts -l "$DataDir\server.log" -w start
        if ($LASTEXITCODE -ne 0) {
            $serverLog = Join-Path $DataDir "server.log"
            if (Test-Path -LiteralPath $serverLog) {
                Get-Content -Encoding UTF8 -LiteralPath $serverLog
            }
            throw "pg_ctl start failed"
        }
        $startedByInvocation = $true
    }
    finally {
        Exit-XpjCleanPostgresEnvironment -Saved $startEnvironment
    }
    Write-Host "Started PostgreSQL on 127.0.0.1:$Port (datadir=$DataDir)"
}

$identity = Assert-XpjOwnedPostgresProcess -DataDir $DataDir -Port $Port -PostgresExe $postgresExe
$clusterOwnership = Assert-XpjTestPostgresOwnership -DataDir $DataDir
$databaseIdentity = "${clusterMarker}:$($clusterOwnership.InstanceId.ToString('D'))"
$passfile = Assert-XpjTestPostgresAuthenticationFiles -DataDir $DataDir -Port $Port
$adminConnection = "host=localhost hostaddr=$($identity.HostAddress) port=$Port user=postgres dbname=postgres connect_timeout=5 require_auth=scram-sha-256 sslmode=disable options='-csearch_path=public,pg_catalog'"
$savedPgEnvironment = Enter-XpjCleanPostgresEnvironment
$env:PGPASSFILE = $passfile
try {
$credential = Read-XpjTestPostgresCredential -DataDir $DataDir
$roleExists = Invoke-XpjPsqlScalar `
    -PsqlExe "$pgbin\psql.exe" `
    -Connection $adminConnection `
    -Query "SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='$applicationRole'" `
    -Label "PostgreSQL application-role lookup" `
    -AllowEmpty
$rolePassword = $credential.Replace("'", "''")
if ($roleExists -ceq '1') {
    Invoke-XpjPsqlCommand `
        -PsqlExe "$pgbin\psql.exe" `
        -Connection $adminConnection `
        -Query "ALTER ROLE `"$applicationRole`" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS PASSWORD '$rolePassword'" `
        -Label "PostgreSQL application-role reset"
}
else {
    Invoke-XpjPsqlCommand `
        -PsqlExe "$pgbin\psql.exe" `
        -Connection $adminConnection `
        -Query "CREATE ROLE `"$applicationRole`" WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS PASSWORD '$rolePassword'" `
        -Label "PostgreSQL application-role creation"
}
$serverDataDir = Invoke-XpjPsqlScalar `
    -PsqlExe "$pgbin\psql.exe" `
    -Connection $adminConnection `
    -Query 'SHOW data_directory' `
    -Label 'PostgreSQL data_directory verification'
$resolvedServerDataDir = [IO.Path]::GetFullPath($serverDataDir).TrimEnd('\', '/')
$resolvedExpectedDataDir = [IO.Path]::GetFullPath($DataDir).TrimEnd('\', '/')
if (-not [string]::Equals($resolvedServerDataDir, $resolvedExpectedDataDir, [StringComparison]::OrdinalIgnoreCase)) {
    throw "PostgreSQL connection reached another data directory: $resolvedServerDataDir"
}

foreach ($db in @($baseDatabase, $smokeDatabase, $restoreDatabase)) {
    $exists = Invoke-XpjPsqlScalar `
        -PsqlExe "$pgbin\psql.exe" `
        -Connection $adminConnection `
        -Query "SELECT 1 FROM pg_catalog.pg_database WHERE datname='$db'" `
        -Label "PostgreSQL database lookup for $db" `
        -AllowEmpty
    if ($exists -cne '1') {
        & "$pgbin\createdb.exe" `
            --no-password `
            "--maintenance-db=$adminConnection" `
            "--owner=$applicationRole" `
            $db
        if ($LASTEXITCODE -ne 0) { throw "createdb $db failed" }
        Write-Host "Created database $db"
    }
    $databaseOwner = Invoke-XpjPsqlScalar `
        -PsqlExe "$pgbin\psql.exe" `
        -Connection $adminConnection `
        -Query "SELECT pg_catalog.pg_get_userbyid(datdba) FROM pg_catalog.pg_database WHERE datname='$db'" `
        -Label "PostgreSQL database owner verification for $db"
    if ($databaseOwner -cne $applicationRole) {
        throw "PostgreSQL database $db is not owned by the test application role."
    }
    $markerQuery = "SELECT pg_catalog.shobj_description(oid, 'pg_database') FROM pg_catalog.pg_database WHERE datname='$db'"
    $actualMarker = Invoke-XpjPsqlScalar `
        -PsqlExe "$pgbin\psql.exe" `
        -Connection $adminConnection `
        -Query $markerQuery `
        -Label "PostgreSQL ownership marker read for $db" `
        -AllowEmpty
    if (
        [string]::IsNullOrWhiteSpace($actualMarker) -or
        $actualMarker -ceq $clusterMarker
    ) {
        Invoke-XpjPsqlCommand `
            -PsqlExe "$pgbin\psql.exe" `
            -Connection $adminConnection `
            -Query "COMMENT ON DATABASE $db IS '$databaseIdentity'" `
            -Label "PostgreSQL ownership marker write for $db"
        $actualMarker = Invoke-XpjPsqlScalar `
            -PsqlExe "$pgbin\psql.exe" `
            -Connection $adminConnection `
            -Query $markerQuery `
            -Label "PostgreSQL ownership marker reread for $db"
    }
    if ($actualMarker -cne $databaseIdentity) {
        throw "Refusing the conflicting database marker on $db"
    }
}
}
finally {
    Exit-XpjCleanPostgresEnvironment -Saved $savedPgEnvironment
}

Write-Host ""
Write-Host "OK: test PostgreSQL ready on $($identity.HostAddress):$Port ($baseDatabase + $smokeDatabase)."
Write-Host "Run the suite from backend\:"
Write-Host "  .\.venv\Scripts\python.exe -m pytest"
}
catch {
    $startFailure = $_
    $rollbackFailure = $null
    if ($startAttemptedByInvocation -and -not $createdCluster) {
        try {
            Stop-XpjPostgresStartedByInvocationIfPresent `
                -DataDir $DataDir `
                -Port $Port `
                -PostgresExe $postgresExe
            if ($startedByInvocation) {
                Write-Host 'Stopped the existing PostgreSQL cluster started by this failed invocation.'
            }
        }
        catch {
            $rollbackFailure = $_
        }
    }
    if ($createdCluster) {
        try {
            $pendingCleanup = Resolve-XpjTestPostgresProvisioning -DataDir $DataDir -Port $Port
            if ($null -ne $pendingCleanup -and -not $pendingCleanup.Completed) {
                Remove-XpjTestPostgresBootstrapPasswordFileIfPresent `
                    -DataDir $pendingCleanup.Provisioning.StagingDir
                Remove-XpjTestPostgresProvisioningGeneration `
                    -DataDir $DataDir `
                    -Port $Port `
                    -InstanceId $pendingCleanup.Provisioning.InstanceId
                Write-Host "Removed the proven failed PostgreSQL provisioning generation."
            }
            else {
                Remove-XpjTestPostgresCluster `
                    -DataDir $DataDir `
                    -Port $Port `
                    -PostgresExe $postgresExe `
                    -ProvisioningInstanceId $provisioningInstanceId
            }
        }
        catch {
            throw "Test PostgreSQL start failed: $($startFailure.Exception.Message) Cleanup also failed: $($_.Exception.Message)"
        }
    }
    if ($null -ne $rollbackFailure) {
        throw "Test PostgreSQL start failed: $($startFailure.Exception.Message) Startup rollback also failed: $($rollbackFailure.Exception.Message)"
    }
    throw $startFailure
}
finally {
    Exit-XpjTestPostgresLifecycleLock -Mutex $lifecycleLock
}
