"""Failure, retry, and forward-only guards for the C07 BIGINT migration."""

from __future__ import annotations

import time

import pytest
from alembic import command
from sqlalchemy import text
from sqlalchemy.exc import OperationalError

from app.database import SessionLocal, engine
from app.database._managed_postgres_migration_runtime import _prearmed_transaction
from app.database._money_schema_attestation import (
    MoneySchemaAttestationError,
    read_money_schema_shape,
)
from app.models import RecurringItem
from app.money_contract import (
    MONEY_COLUMNS_V1,
    MONEY_REMOVED_LEGACY_CHECKS_V1,
)
from tests._infra.c07_money_migration import (
    HEAD_REVISION,
    PREVIOUS_REVISION,
    alembic_config,
    column_type,
    constraint_state,
    current_revision,
    invoke_migration,
    load_migration,
    relfilenode,
    reset_schema,
    run_alembic,
    seed_owner,
)

pytestmark = pytest.mark.real_db


def test_money_widening_uses_caller_transaction_without_c07_context() -> None:
    """Alembic owns the graph; the host owns only the bounded transaction."""

    reset_schema()
    config = alembic_config()
    with engine.connect() as connection, _prearmed_transaction(
        connection,
        timeout_ms=20 * 60 * 1000,
        access_mode="read_write",
    ):
        config.attributes["connection"] = connection
        command.upgrade(config, "head")

    assert current_revision() == "20260809_0001"


def test_frozen_migration_legacy_checks_match_ready_absence_contract() -> None:
    module = load_migration()
    migration_keys = {
        (table, name)
        for table, checks in module._LEGACY_CHECKS.items()
        for name, _predicate in checks
    }
    ready_keys = {
        (check.table, check.name)
        for check in MONEY_REMOVED_LEGACY_CHECKS_V1
    }

    assert migration_keys == ready_keys


def _mutate_money_storage(connection, storage_kind: str) -> None:
    if storage_kind == "domain":
        connection.execute(
            text("CREATE DOMAIN c07_money_domain AS bigint")
        )
        connection.execute(
            text(
                "ALTER TABLE expenses ALTER COLUMN amount_cents "
                "TYPE c07_money_domain "
                "USING amount_cents::bigint::c07_money_domain"
            )
        )
    elif storage_kind == "identity":
        connection.execute(
            text(
                "ALTER TABLE budget_categories "
                "ALTER COLUMN amount_cents "
                "ADD GENERATED BY DEFAULT AS IDENTITY"
            )
        )
    else:
        connection.execute(
            text(
                "ALTER TABLE expense_items "
                "DROP COLUMN unit_price_cents"
            )
        )
        connection.execute(
            text(
                "ALTER TABLE expense_items "
                "ADD COLUMN unit_price_cents bigint "
                "GENERATED ALWAYS AS (0::bigint) STORED"
            )
        )


def test_final_shape_violation_blocks_without_partial_ddl() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    seed_owner()
    with SessionLocal() as db:
        db.add(
            RecurringItem(
                tenant_id="owner",
                merchant_key="legacy-zero",
                merchant_name="legacy-zero",
                baseline_amount_cents=0,
                last_amount_cents=0,
            )
        )
        db.commit()
    before = relfilenode("bill_split_invitations")
    with pytest.raises(Exception, match="target shape"):
        run_alembic(command.upgrade, "head")
    assert current_revision() == PREVIOUS_REVISION
    assert column_type("expenses", "amount_cents") in {"integer", "int4"}
    assert relfilenode("bill_split_invitations") == before


def test_nullability_mismatch_blocks_before_rewrite() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE expenses ALTER COLUMN amount_cents SET NOT NULL"))
    before = relfilenode("bill_split_invitations")
    with pytest.raises(Exception, match="nullability mismatch"):
        run_alembic(command.upgrade, "head")
    assert current_revision() == PREVIOUS_REVISION
    assert relfilenode("bill_split_invitations") == before


def test_mixed_int4_int8_state_fails_closed() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    with engine.begin() as connection:
        connection.execute(text("ALTER TABLE expenses ALTER COLUMN amount_cents TYPE bigint"))
    with pytest.raises(Exception, match="mixed int4/int8"):
        run_alembic(command.upgrade, "head")
    assert current_revision() == PREVIOUS_REVISION


def test_source_server_default_blocks_before_rewrite() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    with engine.begin() as connection:
        connection.execute(
            text(
                "ALTER TABLE expenses "
                "ALTER COLUMN amount_cents SET DEFAULT 0"
            )
        )
    before = relfilenode("bill_split_invitations")

    with pytest.raises(RuntimeError, match="server default mismatch"):
        run_alembic(command.upgrade, "head")

    assert current_revision() == PREVIOUS_REVISION
    assert column_type("expenses", "amount_cents") in {"integer", "int4"}
    assert relfilenode("bill_split_invitations") == before


def test_target_server_default_is_not_accepted_as_completed_shape() -> None:
    reset_schema()
    run_alembic(command.upgrade, "head")
    with engine.begin() as connection:
        connection.execute(
            text(
                "ALTER TABLE expenses "
                "ALTER COLUMN amount_cents SET DEFAULT 0"
            )
        )

    with pytest.raises(RuntimeError, match="server default mismatch"):
        invoke_migration(load_migration())


@pytest.mark.parametrize("storage_kind", ["domain", "identity", "generated"])
def test_source_non_base_storage_semantics_block_before_rewrite(
    storage_kind: str,
) -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    with engine.begin() as connection:
        _mutate_money_storage(connection, storage_kind)
    before = relfilenode("bill_split_invitations")

    with pytest.raises(
        RuntimeError,
        match="server default mismatch|generated/identity/domain",
    ):
        run_alembic(command.upgrade, "head")

    assert current_revision() == PREVIOUS_REVISION
    assert relfilenode("bill_split_invitations") == before


@pytest.mark.parametrize("storage_kind", ["domain", "identity", "generated"])
def test_target_non_base_storage_semantics_are_refused(
    storage_kind: str,
) -> None:
    reset_schema()
    run_alembic(command.upgrade, "head")
    with engine.begin() as connection:
        _mutate_money_storage(connection, storage_kind)

    with pytest.raises(
        RuntimeError,
        match="server default mismatch|generated/identity/domain",
    ):
        invoke_migration(load_migration())


@pytest.mark.parametrize(
    "mode",
    ["wrong_predicate", "not_valid", "no_inherit"],
)
def test_same_name_wrong_or_unvalidated_check_is_refused(mode: str) -> None:
    reset_schema()
    run_alembic(command.upgrade, "head")
    name = "ck_expenses_amount_cents_money_bounds"
    with engine.begin() as connection:
        connection.execute(text(f"ALTER TABLE expenses DROP CONSTRAINT {name}"))
        if mode == "wrong_predicate":
            predicate = "amount_cents IS NULL OR amount_cents >= 0"
            suffix = ""
        else:
            predicate = "amount_cents IS NULL OR (amount_cents BETWEEN 0 AND 9000000000000)"
            suffix = " NOT VALID" if mode == "not_valid" else " NO INHERIT"
        connection.execute(text(f"ALTER TABLE expenses ADD CONSTRAINT {name} CHECK ({predicate}){suffix}"))
    with pytest.raises(RuntimeError, match="constraint mismatch"):
        invoke_migration(load_migration())


def test_all_int8_rerun_adds_only_missing_permanent_check() -> None:
    reset_schema()
    run_alembic(command.upgrade, "head")
    before = {table: relfilenode(table) for table in {column.table for column in MONEY_COLUMNS_V1}}
    name = "ck_expenses_amount_cents_money_bounds"
    with engine.begin() as connection:
        connection.execute(text(f"ALTER TABLE expenses DROP CONSTRAINT {name}"))
    invoke_migration(load_migration())
    assert constraint_state("expenses", name) is not None
    assert {table: relfilenode(table) for table in before} == before


def test_ready_shape_rejects_retained_legacy_check() -> None:
    reset_schema()
    run_alembic(command.upgrade, "head")
    with engine.begin() as connection:
        connection.execute(
            text(
                "ALTER TABLE expenses ADD CONSTRAINT "
                "ck_expenses_amount_non_negative "
                "CHECK (amount_cents IS NULL OR amount_cents >= 0)"
            )
        )
        with pytest.raises(
            MoneySchemaAttestationError,
            match="retained legacy CHECK",
        ):
            read_money_schema_shape(connection)


def test_widen_emits_no_empty_alter_for_rate_only_tables(
    monkeypatch,
) -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    module = load_migration()
    statements: list[str] = []
    monkeypatch.setattr(
        module.op,
        "execute",
        lambda statement: statements.append(str(statement)),
    )

    with engine.connect() as connection:
        module._widen(connection)

    expected_tables = {row[0] for row in module._MANIFEST}
    assert len(statements) == len(expected_tables)
    assert all(" TYPE bigint" in statement for statement in statements)
    assert all(
        "exchange_rates" not in statement and "fx_rates" not in statement
        for statement in statements
    )


def test_table_lock_barrier_rolls_back_before_any_rewrite() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    first = "bill_split_invitations"
    before = relfilenode(first)
    with engine.connect() as blocker:
        blocker.execute(text("LOCK TABLE repayments IN ROW EXCLUSIVE MODE"))
        started = time.perf_counter()
        with pytest.raises(OperationalError):
            run_alembic(command.upgrade, "head")
        elapsed = time.perf_counter() - started
        blocker.rollback()
    assert elapsed < 30
    assert current_revision() == PREVIOUS_REVISION
    assert column_type(first, "amount_cents") in {"integer", "int4"}
    assert relfilenode(first) == before


def test_migration_lease_conflict_has_no_ddl() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    before = relfilenode("bill_split_invitations")
    with engine.connect() as blocker:
        blocker.execute(
            text("SELECT pg_advisory_xact_lock(hashtext(current_database()), hashtext('xiaopiaojia:schema'))")
        )
        with pytest.raises(Exception, match="lease is busy"):
            run_alembic(command.upgrade, "head")
        blocker.rollback()
    assert current_revision() == PREVIOUS_REVISION
    assert relfilenode("bill_split_invitations") == before


def test_mid_migration_failure_rolls_back_all_rewrites(monkeypatch) -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    module = load_migration()

    def fail_after_widen(_bind):
        raise RuntimeError("injected after widen")

    monkeypatch.setattr(module, "_verify_existing_checks", fail_after_widen)
    with pytest.raises(RuntimeError, match="injected after widen"):
        invoke_migration(module)
    assert column_type("expenses", "amount_cents") in {"integer", "int4"}
    assert current_revision() == PREVIOUS_REVISION


def test_money_widening_does_not_raise_schema_compatibility_floor() -> None:
    reset_schema()
    run_alembic(command.upgrade, PREVIOUS_REVISION)
    with engine.connect() as connection:
        before = connection.scalar(text("SELECT value FROM app_meta WHERE key = 'schema_min_compatible'"))
    run_alembic(command.upgrade, "head")
    with engine.connect() as connection:
        after = connection.scalar(text("SELECT value FROM app_meta WHERE key = 'schema_min_compatible'"))
    assert after == before


def test_downgrade_refuses_narrowing() -> None:
    reset_schema()
    run_alembic(command.upgrade, HEAD_REVISION)
    with pytest.raises(Exception, match="forward-only"):
        run_alembic(command.downgrade, PREVIOUS_REVISION)
