"""Schema package facade.

Pre-split callers used ``from app.schemas import <Model>`` against a single
~820-line module. That single import path is preserved — every class is
re-exported here so existing routes, services, and tests need no changes.

Internal layout (one submodule per business domain):

- ``_common``   — error, health, status, auth-check
- ``_identity`` — pairing, ledgers, members, invitations, admin device/link
- ``_exchange`` — FX rate requests / responses
- ``_expense``  — upload, manual create, draft, items, splits, OCR retry
- ``_csv_import``  — CSV import batch / row / apply
- ``_stats``    — category/tag totals, month index, monthly snapshot
- ``_reports``  — trends, rankings, comparisons, lifestyle (imports ExpenseResponse)
- ``_goals``    — spending goals CRUD
- ``_dashboard``— dashboard card visibility / ordering
- ``_rules``    — category rules, merchant aliases, rule-engine apply/preview
- ``_recurring``— recurring candidates and v0.6 formal recurring items
- ``_budgets``  — monthly budget dashboard
- ``_admin``    — data quality, maintenance, server settings, user prefs
"""

from __future__ import annotations

from app.schemas._admin import (
    DataQualitySummaryResponse,
    LearningCleanupReportResponse,
    LearningMaintenanceRunResponse,
    LearningStatusOverviewResponse,
    LearningTableSnapshotResponse,
    MaintenanceAuditCleanupResponse,
    MaintenanceCleanupResponse,
    MaintenanceDeviceCleanupResponse,
    MaintenanceOrphanCleanupResponse,
    ServerSettingsResponse,
    UserUiPreferencesResponse,
    UserUiPreferencesUpdateRequest,
)
from app.schemas._background_task import (
    BackgroundTaskListResponse,
    BackgroundTaskResponse,
    BackgroundTaskStatus,
)
from app.schemas._bill_split import (
    BillSplitAcceptRequest,
    BillSplitInboxListResponse,
    BillSplitInboxResponse,
    BillSplitInviteRequest,
    BillSplitSentListResponse,
    BillSplitSentResponse,
    BillSplitStatus,
)
from app.schemas._budget_advisor import (
    BudgetAdviceDto,
    BudgetAdviseRequest,
    BudgetAdviseResponse,
    BudgetAdvisorStatusResponse,
    BudgetSuggestionDto,
    DiscretionaryResponse,
)
from app.schemas._budgets import (
    BudgetCategoryRequest,
    BudgetCategoryResponse,
    BudgetExcludedCategoryResponse,
    BudgetMonthlyResponse,
    BudgetMonthlyUpdateRequest,
)
from app.schemas._common import (
    AuthCheckResponse,
    ErrorResponse,
    HealthResponse,
    StatusResponse,
)
from app.schemas._csv_import import (
    CsvImportApplyRequest,
    CsvImportApplyResponse,
    CsvImportBatchResponse,
    CsvImportRowResponse,
    CsvImportRowsResponse,
)
from app.schemas._dashboard import (
    DashboardCardResponse,
    DashboardCardsResponse,
    DashboardCardsUpdateRequest,
    DashboardCardUpdateRequest,
)
from app.schemas._exchange import (
    ExchangeRateListResponse,
    ExchangeRateRequest,
    ExchangeRateResponse,
)
from app.schemas._expense import (
    ConfirmedExpenseBatchUpdateRequest,
    ConfirmedExpenseBatchUpdateResponse,
    ExpenseAcknowledgeItemsMismatchRequest,
    ExpenseConfirmRequest,
    ExpenseItemReplaceRequest,
    ExpenseItemRequest,
    ExpenseItemResponse,
    ExpenseItemsResponse,
    ExpenseManualCreateRequest,
    ExpenseMarkNotDuplicateRequest,
    ExpenseOcrRetryRequest,
    ExpenseRecognizeTextRequest,
    ExpenseRejectRequest,
    ExpenseResponse,
    ExpenseSplitReplaceRequest,
    ExpenseSplitRequest,
    ExpenseSplitResponse,
    ExpenseSplitsResponse,
    ExpenseUpdateRequest,
    NotificationDraftCreateRequest,
    OcrRetryResponse,
    PaginatedExpensesResponse,
    PendingCategorySuggestionResponse,
    PendingDuplicateCandidateResponse,
    UploadResponse,
)
from app.schemas._goals import (
    GoalCreateRequest,
    GoalListResponse,
    GoalResponse,
    GoalUpdateRequest,
)
from app.schemas._identity import (
    AdminDeviceRenameRequest,
    AdminDeviceResponse,
    AdminUploadLinkCreateRequest,
    AdminUploadLinkResponse,
    AdminUploadLinkSecretResponse,
    BootstrapOwnerRequest,
    BootstrapOwnerResponse,
    InvitationAcceptRequest,
    InvitationAcceptResponse,
    InvitationCreateRequest,
    InvitationCreateResponse,
    InvitationListResponse,
    InvitationPreviewRequest,
    InvitationPreviewResponse,
    InvitationSummaryResponse,
    LedgerAuditListResponse,
    LedgerAuditResponse,
    LedgerCreateRequest,
    LedgerListResponse,
    LedgerMemberListResponse,
    LedgerMemberResponse,
    LedgerMemberRoleUpdateRequest,
    LedgerResponse,
    LedgerSwitchResponse,
    OwnerTransferResponse,
    PairingCodeCreateRequest,
    PairingCodeResponse,
    PairRequest,
    PairResponse,
    RefreshSessionResponse,
)
from app.schemas._income_plan import (
    IncomePlanCreateRequest,
    IncomePlanListResponse,
    IncomePlanResponse,
    IncomePlanUpdateRequest,
)
from app.schemas._recurring import (
    RecurringCandidateConfirmRequest,
    RecurringCandidateItem,
    RecurringCandidatesResponse,
    RecurringItemListResponse,
    RecurringItemResponse,
)
from app.schemas._reports import (
    LifestyleStatsResponse,
    ReportCategoryComparisonResponse,
    ReportMerchantRankingResponse,
    ReportsOverviewResponse,
    ReportTrendPointResponse,
)
from app.schemas._rules import (
    CategoryRuleCreateRequest,
    CategoryRuleDeleteRequest,
    CategoryRuleResponse,
    CategoryRuleUpdateRequest,
    MerchantAliasCreateRequest,
    MerchantAliasDeleteRequest,
    MerchantAliasListResponse,
    MerchantAliasResponse,
    MerchantAliasUpdateRequest,
    RuleApplicationBatchResponse,
    RuleApplicationListResponse,
    RuleApplicationRollbackResponse,
    RuleApplyConfirmedRequest,
    RuleApplyConfirmedResponse,
    RuleApplyPendingPreviewItem,
    RuleApplyPendingPreviewResponse,
    RuleApplyPendingRequest,
    RuleApplyPendingResponse,
    RulePreviewItem,
    RulePreviewRequest,
    RulePreviewResponse,
)
from app.schemas._stats import (
    CategoriesResponse,
    CategoryStatsResponse,
    MonthlyStatsResponse,
    MonthsResponse,
    TagsResponse,
    TagStatsResponse,
)

__all__ = [
    "AdminDeviceRenameRequest",
    "AdminDeviceResponse",
    "AdminUploadLinkCreateRequest",
    "AdminUploadLinkResponse",
    "AdminUploadLinkSecretResponse",
    "AuthCheckResponse",
    "BackgroundTaskListResponse",
    "BackgroundTaskResponse",
    "BackgroundTaskStatus",
    "BillSplitAcceptRequest",
    "BillSplitInboxListResponse",
    "BillSplitInboxResponse",
    "BillSplitInviteRequest",
    "BillSplitSentListResponse",
    "BillSplitSentResponse",
    "BillSplitStatus",
    "BootstrapOwnerRequest",
    "BootstrapOwnerResponse",
    "BudgetAdviceDto",
    "BudgetAdviseRequest",
    "BudgetAdviseResponse",
    "BudgetAdvisorStatusResponse",
    "BudgetCategoryRequest",
    "BudgetSuggestionDto",
    "BudgetCategoryResponse",
    "BudgetExcludedCategoryResponse",
    "BudgetMonthlyResponse",
    "BudgetMonthlyUpdateRequest",
    "CategoriesResponse",
    "CategoryRuleCreateRequest",
    "CategoryRuleDeleteRequest",
    "CategoryRuleResponse",
    "CategoryRuleUpdateRequest",
    "CategoryStatsResponse",
    "ConfirmedExpenseBatchUpdateRequest",
    "ConfirmedExpenseBatchUpdateResponse",
    "CsvImportApplyRequest",
    "CsvImportApplyResponse",
    "CsvImportBatchResponse",
    "CsvImportRowResponse",
    "CsvImportRowsResponse",
    "DashboardCardResponse",
    "DashboardCardUpdateRequest",
    "DashboardCardsResponse",
    "DashboardCardsUpdateRequest",
    "DataQualitySummaryResponse",
    "DiscretionaryResponse",
    "ErrorResponse",
    "ExchangeRateListResponse",
    "ExchangeRateRequest",
    "ExchangeRateResponse",
    "ExpenseConfirmRequest",
    "ExpenseItemReplaceRequest",
    "ExpenseItemRequest",
    "ExpenseItemResponse",
    "ExpenseItemsResponse",
    "ExpenseManualCreateRequest",
    "ExpenseMarkNotDuplicateRequest",
    "ExpenseOcrRetryRequest",
    "ExpenseAcknowledgeItemsMismatchRequest",
    "ExpenseRecognizeTextRequest",
    "ExpenseRejectRequest",
    "ExpenseResponse",
    "ExpenseSplitReplaceRequest",
    "ExpenseSplitRequest",
    "ExpenseSplitResponse",
    "ExpenseSplitsResponse",
    "ExpenseUpdateRequest",
    "GoalCreateRequest",
    "GoalListResponse",
    "GoalResponse",
    "GoalUpdateRequest",
    "HealthResponse",
    "IncomePlanCreateRequest",
    "IncomePlanListResponse",
    "IncomePlanResponse",
    "IncomePlanUpdateRequest",
    "InvitationAcceptRequest",
    "InvitationAcceptResponse",
    "InvitationCreateRequest",
    "InvitationCreateResponse",
    "InvitationListResponse",
    "InvitationPreviewRequest",
    "InvitationPreviewResponse",
    "InvitationSummaryResponse",
    "LedgerAuditListResponse",
    "LedgerAuditResponse",
    "LedgerCreateRequest",
    "LedgerListResponse",
    "LedgerMemberListResponse",
    "LedgerMemberResponse",
    "LedgerMemberRoleUpdateRequest",
    "LedgerResponse",
    "LedgerSwitchResponse",
    "LearningCleanupReportResponse",
    "LearningMaintenanceRunResponse",
    "LearningStatusOverviewResponse",
    "LearningTableSnapshotResponse",
    "LifestyleStatsResponse",
    "MaintenanceAuditCleanupResponse",
    "MaintenanceCleanupResponse",
    "MaintenanceDeviceCleanupResponse",
    "MaintenanceOrphanCleanupResponse",
    "MerchantAliasCreateRequest",
    "MerchantAliasDeleteRequest",
    "MerchantAliasListResponse",
    "MerchantAliasResponse",
    "MerchantAliasUpdateRequest",
    "MonthlyStatsResponse",
    "MonthsResponse",
    "NotificationDraftCreateRequest",
    "OcrRetryResponse",
    "OwnerTransferResponse",
    "PaginatedExpensesResponse",
    "PairRequest",
    "PairResponse",
    "PendingCategorySuggestionResponse",
    "PendingDuplicateCandidateResponse",
    "RefreshSessionResponse",
    "PairingCodeCreateRequest",
    "PairingCodeResponse",
    "RecurringCandidateConfirmRequest",
    "RecurringCandidateItem",
    "RecurringCandidatesResponse",
    "RecurringItemListResponse",
    "RecurringItemResponse",
    "ReportCategoryComparisonResponse",
    "ReportMerchantRankingResponse",
    "ReportTrendPointResponse",
    "ReportsOverviewResponse",
    "RuleApplicationBatchResponse",
    "RuleApplicationListResponse",
    "RuleApplicationRollbackResponse",
    "RuleApplyConfirmedRequest",
    "RuleApplyConfirmedResponse",
    "RuleApplyPendingPreviewItem",
    "RuleApplyPendingPreviewResponse",
    "RuleApplyPendingRequest",
    "RuleApplyPendingResponse",
    "RulePreviewItem",
    "RulePreviewRequest",
    "RulePreviewResponse",
    "ServerSettingsResponse",
    "StatusResponse",
    "TagStatsResponse",
    "TagsResponse",
    "UploadResponse",
    "UserUiPreferencesResponse",
    "UserUiPreferencesUpdateRequest",
]
