from __future__ import annotations

import os
import sys
from collections.abc import Generator
from pathlib import Path

import pytest

from scripts.packaging_pytest_contract import (
    PACKAGING_EXPECTED_PARALLEL_COUNT_ENV,
    PACKAGING_EXPECTED_PARALLEL_DIGEST_ENV,
    PACKAGING_EXPECTED_SERIAL_COUNT_ENV,
    PACKAGING_EXPECTED_SERIAL_DIGEST_ENV,
    PACKAGING_HERMETIC_RESOURCE,
    PACKAGING_PARALLEL_MARKER,
    PACKAGING_RESOURCE_MARKER,
    PACKAGING_RESOURCES,
    PACKAGING_SERIAL_MARKER,
    packaging_partition_violation,
    packaging_resource_membership_marker,
    packaging_xdist_group,
)
from scripts.pytest_execution_contract import (
    PYTEST_EXPECTED_COUNT_ENV,
    PYTEST_EXPECTED_DIGEST_ENV,
    PYTEST_HANDSHAKE_PATH_ENV,
    PYTEST_HANDSHAKE_TOKEN_ENV,
)
from scripts.pytest_execution_contract import (
    pytest_execution_handshake_payload as execution_handshake_payload,
)
from scripts.pytest_execution_contract import (
    pytest_execution_membership_violation as execution_membership_violation,
)
from scripts.test_pg_contract import start_windows_parent_watchdog

_STRICT_RUNTIME_ENV = "XPJ_REQUIRE_WINDOWS_LIFECYCLE_RUNTIME"
_PACKAGING_TESTS_ROOT = Path(__file__).resolve().parent


def _strict_runtime_enabled() -> bool:
    return os.environ.get(_STRICT_RUNTIME_ENV) == "1"


def _is_xdist_worker(config: pytest.Config) -> bool:
    return hasattr(config, "workerinput")


def _xdist_worker_id(node: object) -> str:
    return str(node.gateway.id)  # type: ignore[attr-defined]


def _register_markers(config: pytest.Config) -> None:
    config.addinivalue_line(
        "markers",
        "packaging_resource(name): explicit packaging test resource authority; "
        "the closest declaration wins so a test may override its module default.",
    )
    config.addinivalue_line(
        "markers",
        "packaging_parallel: generated scheduler membership; tests must not author it.",
    )
    config.addinivalue_line(
        "markers",
        "packaging_serial: generated scheduler membership; tests must not author it.",
    )
    config.addinivalue_line(
        "markers",
        "xdist_group(name): generated by the packaging resource contract.",
    )
    for resource in sorted(PACKAGING_RESOURCES):
        config.addinivalue_line(
            "markers",
            f"{packaging_resource_membership_marker(resource)}: generated exact "
            "packaging resource membership; tests must not author it.",
        )


def _initialize_runner_state(config: pytest.Config) -> None:
    config._xpj_xdist_ready_workers = set()  # type: ignore[attr-defined]
    config._xpj_xdist_down_workers = set()  # type: ignore[attr-defined]
    config._xpj_xdist_worker_errors = {}  # type: ignore[attr-defined]


def _start_strict_runtime_watchdog(config: pytest.Config) -> None:
    role = "xdist worker" if _is_xdist_worker(config) else "controller"
    start_windows_parent_watchdog(label=f"strict packaging pytest {role}")


def _resource_for_item(item: pytest.Item) -> str:
    declarations = list(item.iter_markers_with_node(name=PACKAGING_RESOURCE_MARKER))
    if not declarations:
        raise pytest.UsageError(
            f"{item.nodeid} lacks an explicit packaging_resource declaration"
        )
    declarations_by_scope: dict[int, int] = {}
    for node, _marker in declarations:
        scope = id(node)
        declarations_by_scope[scope] = declarations_by_scope.get(scope, 0) + 1
    if any(count != 1 for count in declarations_by_scope.values()):
        raise pytest.UsageError(
            f"{item.nodeid} declares packaging_resource more than once at one scope"
        )
    marker = declarations[0][1]
    if marker.kwargs or len(marker.args) != 1 or not isinstance(marker.args[0], str):
        raise pytest.UsageError(
            f"{item.nodeid} must declare packaging_resource with one string argument"
        )
    resource = marker.args[0]
    if resource not in PACKAGING_RESOURCES:
        raise pytest.UsageError(
            f"{item.nodeid} declares unknown packaging resource {resource!r}"
        )
    return resource


def _validate_managed_xdist(config: pytest.Config) -> None:
    if not _strict_runtime_enabled():
        return
    violations: list[str] = []
    if not (
        config.pluginmanager.hasplugin("xdist.plugin")
        or config.pluginmanager.hasplugin("xdist")
    ):
        violations.append("strict packaging contracts require the xdist plugin")
    if _is_xdist_worker(config):
        if violations:
            raise pytest.UsageError(" | ".join(violations))
        return
    if config.getoption("numprocesses", default=0) != 3:
        violations.append("strict packaging contracts require exactly 3 xdist workers")
    if str(config.getoption("dist", default="")) != "loadgroup":
        violations.append("strict packaging contracts require xdist loadgroup scheduling")
    try:
        max_worker_restarts = int(
            config.getoption("maxworkerrestart", default=-1)
        )
    except (TypeError, ValueError):
        max_worker_restarts = -1
    if max_worker_restarts != 0:
        violations.append("strict packaging contracts forbid xdist worker restarts")
    if violations:
        raise pytest.UsageError(" | ".join(violations))


def pytest_configure(config: pytest.Config) -> None:
    _initialize_runner_state(config)
    _register_markers(config)
    _validate_managed_xdist(config)
    if not _strict_runtime_enabled():
        return
    _start_strict_runtime_watchdog(config)
    violations: list[str] = []
    if config.getoption("collectonly", default=False):
        violations.append("strict packaging contracts must execute, not only collect")
    if len(config.args) != 1:
        violations.append("strict packaging contracts must collect the complete root")
    else:
        try:
            collection_root = Path(config.args[0]).resolve()
        except OSError:
            collection_root = Path()
        if collection_root != _PACKAGING_TESTS_ROOT:
            violations.append("strict packaging contracts must collect the complete root")
    if (
        (config.getoption("keyword", default="") or "").strip()
        or (config.getoption("markexpr", default="") or "").strip()
        or config.getoption("deselect", default=())
        or config.getoption("ignore", default=())
        or config.getoption("ignore_glob", default=())
        or config.getoption("lf", default=False)
        or sys.flags.optimize
    ):
        violations.append("strict packaging contracts must not filter the test set")
    handshake_path = os.environ.get(PYTEST_HANDSHAKE_PATH_ENV)
    handshake_token = os.environ.get(PYTEST_HANDSHAKE_TOKEN_ENV)
    if (
        not handshake_path
        or not handshake_token
        or not os.environ.get(PYTEST_EXPECTED_COUNT_ENV)
        or not os.environ.get(PYTEST_EXPECTED_DIGEST_ENV)
        or not os.environ.get(PACKAGING_EXPECTED_PARALLEL_COUNT_ENV)
        or not os.environ.get(PACKAGING_EXPECTED_PARALLEL_DIGEST_ENV)
        or not os.environ.get(PACKAGING_EXPECTED_SERIAL_COUNT_ENV)
        or not os.environ.get(PACKAGING_EXPECTED_SERIAL_DIGEST_ENV)
    ):
        violations.append("strict packaging contracts are missing execution proof inputs")
    elif not _is_xdist_worker(config) and Path(handshake_path).exists():
        violations.append("strict packaging completion handshake already exists")
    if violations:
        raise pytest.UsageError(" | ".join(violations))


@pytest.hookimpl(optionalhook=True)
def pytest_testnodeready(node: object) -> None:
    node.config._xpj_xdist_ready_workers.add(_xdist_worker_id(node))  # type: ignore[attr-defined]


@pytest.hookimpl(optionalhook=True)
def pytest_testnodedown(node: object, error: object | None) -> None:
    worker_id = _xdist_worker_id(node)
    node.config._xpj_xdist_down_workers.add(worker_id)  # type: ignore[attr-defined]
    if error is not None:
        node.config._xpj_xdist_worker_errors[worker_id] = str(error)  # type: ignore[attr-defined]


def _generated_scheduler_marker_violation(
    item: pytest.Item,
    resource: str,
) -> str | None:
    exact_resource = packaging_resource_membership_marker(resource)
    expected_lane = (
        PACKAGING_PARALLEL_MARKER
        if resource == PACKAGING_HERMETIC_RESOURCE
        else PACKAGING_SERIAL_MARKER
    )
    for marker_name in (
        PACKAGING_PARALLEL_MARKER,
        PACKAGING_SERIAL_MARKER,
        *(packaging_resource_membership_marker(name) for name in sorted(PACKAGING_RESOURCES)),
    ):
        count = sum(1 for _node, _marker in item.iter_markers_with_node(marker_name))
        expected_count = 1 if marker_name in {exact_resource, expected_lane} else 0
        if count != expected_count:
            return (
                f"{item.nodeid} has invalid generated marker {marker_name}: "
                f"expected={expected_count}, actual={count}"
            )
    groups = tuple(
        marker
        for _node, marker in item.iter_markers_with_node("xdist_group")
    )
    if resource == PACKAGING_HERMETIC_RESOURCE:
        return None if not groups else f"{item.nodeid} must not have an xdist group"
    expected_group = packaging_xdist_group(resource)
    if (
        len(groups) != 1
        or groups[0].args != (expected_group,)
        or groups[0].kwargs
    ):
        return f"{item.nodeid} does not have exactly one generated {expected_group} group"
    return None


@pytest.hookimpl(wrapper=True, tryfirst=True)
def pytest_collection_modifyitems(
    items: list[pytest.Item],
) -> Generator[None, None, None]:
    original_items = tuple(items)
    original_nodeids = tuple(item.nodeid for item in original_items)
    parallel_nodeids: list[str] = []
    serial_nodeids: list[str] = []
    resource_assignments: list[tuple[pytest.Item, str]] = []
    for item in items:
        authored_scheduler_markers = [
            name
            for name in (
                PACKAGING_PARALLEL_MARKER,
                PACKAGING_SERIAL_MARKER,
                "xdist_group",
                *(
                    packaging_resource_membership_marker(resource)
                    for resource in sorted(PACKAGING_RESOURCES)
                ),
            )
            if item.get_closest_marker(name) is not None
        ]
        if authored_scheduler_markers:
            raise pytest.UsageError(
                f"{item.nodeid} must not author generated scheduler marker(s): "
                + ", ".join(authored_scheduler_markers)
            )
        resource = _resource_for_item(item)
        resource_assignments.append((item, resource))
        item.add_marker(packaging_resource_membership_marker(resource))
        if resource == PACKAGING_HERMETIC_RESOURCE:
            parallel_nodeids.append(item.nodeid)
            item.add_marker(PACKAGING_PARALLEL_MARKER)
        else:
            serial_nodeids.append(item.nodeid)
            item.add_marker(PACKAGING_SERIAL_MARKER)
            item.add_marker(pytest.mark.xdist_group(packaging_xdist_group(resource)))
    partition_violation = packaging_partition_violation(
        original_nodeids,
        parallel_nodeids,
        serial_nodeids,
    )
    if partition_violation:
        raise pytest.UsageError(partition_violation)
    yield
    for item, resource in resource_assignments:
        marker_violation = _generated_scheduler_marker_violation(item, resource)
        if marker_violation:
            raise pytest.UsageError(marker_violation)
    if not _strict_runtime_enabled():
        return
    if tuple(id(item) for item in items) != tuple(id(item) for item in original_items):
        raise pytest.UsageError(
            "strict packaging contracts changed the independently collected item set"
        )
    violation = execution_membership_violation(
        label="packaging",
        selected_nodeids=original_nodeids,
        expected_count=os.environ.get(PYTEST_EXPECTED_COUNT_ENV),
        expected_digest=os.environ.get(PYTEST_EXPECTED_DIGEST_ENV),
    )
    if violation is None:
        violation = execution_membership_violation(
            label="packaging parallel resource",
            selected_nodeids=parallel_nodeids,
            expected_count=os.environ.get(PACKAGING_EXPECTED_PARALLEL_COUNT_ENV),
            expected_digest=os.environ.get(PACKAGING_EXPECTED_PARALLEL_DIGEST_ENV),
            allow_empty=True,
        )
    if violation is None:
        violation = execution_membership_violation(
            label="packaging serial resource",
            selected_nodeids=serial_nodeids,
            expected_count=os.environ.get(PACKAGING_EXPECTED_SERIAL_COUNT_ENV),
            expected_digest=os.environ.get(PACKAGING_EXPECTED_SERIAL_DIGEST_ENV),
            allow_empty=True,
        )
    if violation:
        raise pytest.UsageError(violation)


@pytest.hookimpl(trylast=True)
def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    """Require every independently collected packaging proof to pass normally."""

    if not _strict_runtime_enabled():
        return
    if _is_xdist_worker(session.config):
        return
    terminal = session.config.pluginmanager.get_plugin("terminalreporter")
    skipped = sorted(
        {
            report.nodeid
            for report in (() if terminal is None else terminal.stats.get("skipped", ()))
        }
    )
    violations: list[str] = []
    if sys.platform != "win32":
        violations.append("strict Windows lifecycle contracts require a Windows runner")
    if skipped:
        violations.append(
            f"strict packaging contracts skipped {len(skipped)} collection or test report(s): "
            + ", ".join(skipped[:3])
        )
    forbidden = {
        name: len(terminal.stats.get(name, ()))
        for name in ("xfailed", "xpassed")
        if terminal is not None and terminal.stats.get(name)
    }
    if forbidden:
        violations.append(
            "strict packaging contracts forbid tolerated outcomes: "
            + ", ".join(f"{name}={count}" for name, count in forbidden.items())
        )
    ready_workers = session.config._xpj_xdist_ready_workers  # type: ignore[attr-defined]
    down_workers = session.config._xpj_xdist_down_workers  # type: ignore[attr-defined]
    worker_errors = session.config._xpj_xdist_worker_errors  # type: ignore[attr-defined]
    if worker_errors or len(ready_workers) != 3 or down_workers != ready_workers:
        violations.append(
            "strict packaging contracts did not observe clean completion from all "
            f"xdist workers: ready={sorted(ready_workers)}, "
            f"down={sorted(down_workers)}, errors={worker_errors}"
        )
    passed_count = len(terminal.stats.get("passed", ())) if terminal is not None else None
    if (
        exitstatus != pytest.ExitCode.OK
        or passed_count is None
        or session.testscollected <= 0
        or passed_count != session.testscollected
    ):
        violations.append("strict packaging contracts did not complete every collected test normally")
    if violations:
        if terminal is not None:
            terminal.write_sep("!", " | ".join(violations), red=True)
        session.exitstatus = pytest.ExitCode.TESTS_FAILED
        return

    handshake_path = Path(os.environ[PYTEST_HANDSHAKE_PATH_ENV])
    try:
        with handshake_path.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(
                execution_handshake_payload(
                    "packaging",
                    os.environ[PYTEST_HANDSHAKE_TOKEN_ENV],
                    int(os.environ[PYTEST_EXPECTED_COUNT_ENV]),
                    os.environ[PYTEST_EXPECTED_DIGEST_ENV],
                )
            )
    except OSError:
        if terminal is not None:
            terminal.write_sep(
                "!",
                "strict packaging contracts could not create their completion handshake",
                red=True,
            )
        session.exitstatus = pytest.ExitCode.TESTS_FAILED
