# Regenerate the local Web font bundle. Run from any directory; generated assets
# are committed and served locally, with no runtime request to Google Fonts.
param([string]$Proxy)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $repoRoot "backend/app/static/web/fonts"
$request = @{
    UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    UseBasicParsing = $true
    TimeoutSec = 60
}
if ($Proxy) { $request.Proxy = $Proxy }

# Keep every unicode-range. A CJK response is a collection of complementary
# subsets, not a list from which one 'main Chinese' subset can be selected.
$families = @(
    @{ Query = "Noto+Sans+SC:wght@400..800"; Upstream = "Noto Sans SC"; Local = "Ticketbox Sans"; Prefix = "NotoSansSC"; License = "notosanssc" },
    @{ Query = "Inter:wght@400..800"; Upstream = "Inter"; Local = "Ticketbox Figures"; Prefix = "Inter"; License = "inter" }
)
$generated = [System.Collections.Generic.List[string]]::new()
$generated.Add("/* Generated by scripts/download-fonts.ps1. Local variable fonts; preserve unicode-range. */")
$utf8 = [System.Text.UTF8Encoding]::new($false)

foreach ($family in $families) {
    $url = "https://fonts.googleapis.com/css2?family=$($family.Query)&display=swap"
    $css = (Invoke-WebRequest -Uri $url @request).Content
    $blocks = [regex]::Matches($css, "@font-face\s*\{[^}]+\}")
    if ($blocks.Count -eq 0) { throw "No font faces returned for $($family.Upstream)" }
    $generated.Add("/* Source: $url */")
    $seen = @{}
    $index = 0
    foreach ($block in $blocks) {
        $source = ([regex]::Match($block.Value, "url\(([^)]+\.woff2)\)")).Groups[1].Value
        if (-not $source -or $block.Value -notmatch "unicode-range:") {
            throw "Expected a WOFF2 unicode subset for $($family.Upstream)"
        }
        if (-not $seen.ContainsKey($source)) {
            $download = Join-Path $outDir "$($family.Prefix).download"
            Invoke-WebRequest -Uri $source -OutFile $download @request
            $digest = (Get-FileHash -LiteralPath $download -Algorithm SHA256).Hash.ToLowerInvariant()
            $filename = "$($family.Prefix)-$($digest.Substring(0, 16)).woff2"
            Move-Item -LiteralPath $download -Destination (Join-Path $outDir $filename) -Force
            $seen[$source] = $filename
        }
        $face = $block.Value.Replace("'$($family.Upstream)'", "'$($family.Local)'").Replace($source, $seen[$source])
        $generated.Add($face)
        $index++
        Write-Progress -Activity "Download $($family.Upstream)" -Status "$index / $($blocks.Count)" -PercentComplete (100 * $index / $blocks.Count)
    }
    Write-Progress -Activity "Download $($family.Upstream)" -Completed
    $licenseUrl = "https://raw.githubusercontent.com/google/fonts/main/ofl/$($family.License)/OFL.txt"
    $license = (Invoke-WebRequest -Uri $licenseUrl @request).Content -replace '(?m)[ \t]+(?=\r?$)', ''
    [System.IO.File]::WriteAllText((Join-Path $outDir "$($family.Prefix)-OFL.txt"), $license, $utf8)
    Write-Output "$($family.Upstream): $($blocks.Count) faces, $($seen.Count) local font files"
}

[System.IO.File]::WriteAllText((Join-Path $outDir "fonts.css"), ($generated -join "`n`n") + "`n", $utf8)
Write-Output "Updated local fonts.css. Review generated assets and remove superseded font files before committing."
